# Generated by Django 2.2.11 on 2020-03-26 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dsc_movie', models.TextField(verbose_name='Movie Description')),
                ('flag_computed', models.SmallIntegerField()),
                ('qtd_likes', models.IntegerField(default=0, verbose_name='Likes')),
                ('qtd_dislikes', models.IntegerField(default=0, verbose_name='Dislikes')),
                ('ranking', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Ranking')),
            ],
            options={
                'verbose_name': 'Movies',
                'verbose_name_plural': 'Movies',
                'db_table': 'movies',
            },
        ),
        migrations.CreateModel(
            name='MoviesCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dsc_category', models.CharField(max_length=100, verbose_name='Category')),
                ('sum_likes', models.IntegerField(default=0, verbose_name='Total Likes')),
                ('sum_dislikes', models.IntegerField(default=0, verbose_name='Total Dislikes')),
                ('ranking', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Ranking')),
            ],
            options={
                'verbose_name': 'Movies Category',
                'verbose_name_plural': 'Movies Category',
                'db_table': 'movies_category',
            },
        ),
        migrations.CreateModel(
            name='MoviesVotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_movie', models.IntegerField(default=0, verbose_name='Vote')),
                ('fk_movies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Movies', verbose_name='Movie')),
                ('fk_movies_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.MoviesCategory', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Movies Votes',
                'verbose_name_plural': 'Movies Votes',
                'db_table': 'movies_votes',
            },
        ),
        migrations.AddField(
            model_name='movies',
            name='fk_movies_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.MoviesCategory', verbose_name='Category'),
        ),
    ]
